// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

import ZenSpacesKit

/// The closest SF Symbol to each of Zen's built-in space icons
/// (`SpaceIcon.zenIconNames`), since their chrome:// SVGs cannot load here.
enum ZenSpaceIconSymbols {
    static func symbol(for zenIcon: String) -> String {
        symbols[zenIcon] ?? "circle.fill"
    }

    private static let symbols: [String: String] = [
        "airplane": "airplane",
        "american-football": "football.fill",
        "baseball": "baseball.fill",
        "basket": "basket.fill",
        "bed": "bed.double.fill",
        "bell": "bell.fill",
        "bookmark": "bookmark.fill",
        "book": "book.fill",
        "briefcase": "briefcase.fill",
        "brush": "paintbrush.fill",
        "bug": "ladybug.fill",
        "build": "hammer.fill",
        "cafe": "cup.and.saucer.fill",
        "call": "phone.fill",
        "card": "creditcard.fill",
        "chat": "bubble.left.and.bubble.right.fill",
        "checkbox": "checkmark.square.fill",
        "circle": "circle.fill",
        "cloud": "cloud.fill",
        "code": "chevron.left.forwardslash.chevron.right",
        "coins": "dollarsign.circle.fill",
        "construct": "wrench.and.screwdriver.fill",
        "cutlery": "fork.knife",
        "egg": "oval.fill",
        "extension-puzzle": "puzzlepiece.extension.fill",
        "eye": "eye.fill",
        "fast-food": "takeoutbag.and.cup.and.straw.fill",
        "fish": "fish.fill",
        "flag": "flag.fill",
        "flame": "flame.fill",
        "flask": "flask.fill",
        "folder": "folder.fill",
        "game-controller": "gamecontroller.fill",
        "globe-1": "globe.americas.fill",
        "globe": "globe",
        "grid-2x2": "square.grid.2x2.fill",
        "grid-3x3": "square.grid.3x3.fill",
        "heart": "heart.fill",
        "ice-cream": "birthday.cake.fill",
        "image": "photo.fill",
        "inbox": "tray.fill",
        "key": "key.fill",
        "layers": "square.3.layers.3d",
        "leaf": "leaf.fill",
        "lightning": "bolt.fill",
        "location": "location.fill",
        "lock-closed": "lock.fill",
        "logo-rss": "dot.radiowaves.up.forward",
        "logo-usd": "dollarsign",
        "mail": "envelope.fill",
        "map": "map.fill",
        "megaphone": "megaphone.fill",
        "moon": "moon.fill",
        "music": "music.note",
        "navigate": "location.north.fill",
        "nuclear": "atom",
        "page": "doc.fill",
        "palette": "paintpalette.fill",
        "paw": "pawprint.fill",
        "people": "person.2.fill",
        "pizza": "triangle.fill",
        "planet": "globe.europe.africa.fill",
        "present": "gift.fill",
        "rocket": "paperplane.fill",
        "school": "graduationcap.fill",
        "shapes": "square.on.circle.fill",
        "shirt": "tshirt.fill",
        "skull": "exclamationmark.octagon.fill",
        "squares": "square.on.square.fill",
        "square": "square.fill",
        "star-1": "sparkle",
        "star": "star.fill",
        "stats-chart": "chart.bar.fill",
        "sun": "sun.max.fill",
        "tada": "party.popper.fill",
        "terminal": "terminal.fill",
        "ticket": "ticket.fill",
        "time": "clock.fill",
        "trash": "trash.fill",
        "triangle": "triangle.fill",
        "video": "video.fill",
        "volume-high": "speaker.wave.3.fill",
        "wallet": "wallet.pass.fill",
        "warning": "exclamationmark.triangle.fill",
        "water": "drop.fill",
        "weight": "scalemass.fill",
    ]
}
